- name: Détection de la technologie 
  hosts: all
  gather_facts: true

  tasks:
  - name: Affichage de la technologie
    debug:
      msg: "L'appareil est du type : {{ansible_network_os}}"
  
  - name: trouvé cisco
    debug:
      msg: "L'appareil est du type : Cisco"
    when: ansible_network_os == 'cisco.ios.ios'
    

  - name: trouvé pfsense
    debug:
      msg: "L'appareil est du type : pfsense"
    when: ansible_network_os == 'pfsense'

  - name: Appareils Cisco
    include_role:
      name: cisco
    when: ansible_network_os == 'cisco.ios.ios'

  - name: Appareils Pfsense
    include_role:
      name: pfsense
    when: ansible_network_os == 'pfsense'

  
 

