- name: Corriger la configuration sur base de ce qui est écrit dans le rapport
  vars_prompt:
    - name: validation
      prompt: "Corriger la configuration sur base de ce qui est écrit dans le rapport ? (yes/no)"
      private: no