- name: cherrypick fzfdf
  shell: |
    cat {{ ansible_config_file | dirname }}/correctif/{{ inventory_hostname }}_nok.txt | {{ ansible_config_file | dirname }}/tools/fzf --multi --prompt="Choississez les commandes à corriger :"
  register: user_selection


