#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/pfsense

-name: Récupération de la configuration sur pfsense
  -task:
    name: Récupération config pfSense
    hosts: all
    gather_facts: no
