- name: Cherry-picking des commandes à ajouter en fonction de leurs numéros/titres
  pause:
    prompt: "Veuillez enter le numéro de la commande manquante à corriger"
  register: user_titre_num

- name: debug
  debug:
    msg: "{{(cis_rules | selectattr('titre', 'equalto', user_titre_num))|list}}" 

- name: Récupération du titre de la commande
  set_fact:
    titre_num: "{{(cis_rules | selectattr('titre', 'equalto', user_titre_num)) }}"
  
- name: Appliquer la modification sur la configuration
  cisco.ios.ios_command:
    commands: "{{ titre_num['command'] }}"
