
- name: charger règles cis
  include_vars:
    file: "{{ ansible_config_file | dirname }}/cis_ios15_complet.yml"
    name: cis

- name: cherrypick fzfdf
  include_tasks: "{{ ansible_config_file | dirname }}/tasks/fzf-cherrypick.yml"
  register: user_selection

- name: commandes choisies
  set_fact:
    com_choisies: "{{ com_choisies | default([]) + [[item.split(':')[0] | trim, item.split(':')[1] | trim]] }}"
  loop: "{{ user_selection.stdout_lines }}"

- name: debug2
  debug:
    var: com_choisies


- name: demande paramètres pour commande (laisser vide si pas de paramètres)
  pause:
    prompt: "Veuillez entrer un paramètre pour la commande {{ item[1] }}(laisser vide si pas de paramètres)"
  loop: "{{ com_choisies }}"
  loop_control:
    label: "{{ item[1] }}"
  register: user_params

- name: Concat commande et paramètres
  set_fact:
    commandes_param: "{{lookup('template', 'templates/commande_corrige.jinja')| trim |from_yaml }}"


- name: debug 3
  debug:
    var: commandes_param


- name: Appliquer la modification sur la configuration
  cisco.ios.ios_config:
    lines: "{{ item }}"
    match: line
  loop: "{{commandes_param}}"
