- name: backup config 
  copy:
    src: "{{ ansible_config_file | dirname }}/configs/{{ inventory_hostname }}_running_config.txt"
    dest: "{{ ansible_config_file | dirname }}/configs/backup/backup_{{ inventory_hostname }}_running_config.txt"


- name: Création du fichier de correction
  ansible.builtin.template:
    src: "{{ ansible_config_file | dirname }}/roles/cisco/templates/template_correctif.jinja"
    dest : "{{ ansible_config_file | dirname }}/correctif/{{ inventory_hostname }}_correctif.txt"

- name: Récupération du fichier des commandes manquantes sur la machine
  set_fact:
    missing_commands: "{{ lookup('file', (ansible_config_file | dirname) + '/correctif/' + inventory_hostname + '_correctif.txt') }}"

- name: Demander la confirmation pour appliquer les modifs sur la config
  pause:
    prompt: "Êtes-vous certain d'appliquer les modifications sur la configuration ? (yes/no)"
  register: validation

- name: Correction de la configuration
  cisco.ios.ios_command:
    commands: "{{missing_commands.splitlines()}}"
  when: validation.user_input == "yes"