#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/cisco

- name: Tâche connexion appareil cisco
  #connection:local
  #become: yes
  #hosts: "{{ ansible_host }}"

  set_fact:
    cli:
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      timeout: 100
  
- name: récupération de la configuration sur la machine
  include_tasks: rapport.yml

- name: Demander la confirmation pour appliquer les modifs sur la config
  pause:
    prompt: "Voulez-vous appliquer les toutes les corrections sur la configuration ? (yes/no)"
  register: correction_auto


- name: Correction de tout le fichier de configuration sur la machine
  include_tasks: correction.yml
  when: correction_auto.user_input == "yes"

- name: Cherry-pick sur les corrections ?
  pause:
    prompt: "Voulez-vous choisir les lignes à corriger dans la configuration ? (yes/no)"
    register: cherry_pick

- name: Lancement du cherry-pick
  include_tasks: cherry-pick.yml
  when: cherry_pick.user_input == "yes"
