#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/cisco

- name: Tâche connexion appareil cisco
  #connection:local
  #become: yes
  #hosts: "{{ ansible_host }}"

  set_fact:
    cli:
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      timeout: 100
  
- name: récupération de la configuration sur la machine
  include_tasks: rapport.yml

- name: Demander la confirmation pour appliquer les modifs sur la config
  pause:
    prompt: "Voulez-vous appliquer les modifications sur la configuration ? (yes/no)"
  register: validation

- name: Variable de débug pour validation
  debug:
    var: validation

- name: Correction de tout le fichier de configuration sur la machine
  include_tasks: correction.yml
  when: validation.user_input == "yes"